$(info build makefile oplus_powermodel_gpu_utility.ko CONFIG_OPLUS_FEATURE_POWERMODEL_GPU_INTERFACE = $(CONFIG_OPLUS_FEATURE_POWERMODEL_GPU_INTERFACE))
$(info build makefile oplus_powermodel_gpu_utility.ko CONFIG_OPLUS_FEATURE_POWERMODEL = $(CONFIG_OPLUS_FEATURE_POWERMODEL))

obj-$(CONFIG_OPLUS_FEATURE_POWERMODEL_GPU_INTERFACE) += oplus_powermodel_gpu_utility.o
